stages:
  - release


.debian-release:
  stage: release
  tags: [ linux ]
  needs: []
  image: python:3.9-bullseye
  script:
    - echo "installing boost-python and boost-locale"
    - apt-get update && apt-get install -yqq --no-install-recommends libboost-python-dev libboost-locale-dev
    - echo "downloading planckWrapper ref:${WRAPPER_REF}"
    - wrapperURL="https://git.planck.security/api/v4/projects/406/jobs/artifacts/${WRAPPER_REF}/raw/libPlanckWrapper.tar.gz?job=debian-${WRAPPER_REF}-release"
    - curl --location --header "PRIVATE-TOKEN:${GITLAB_ACCESS_TOKEN}" ${wrapperURL} --output libPlanckWrapper.tar.gz
    - tar -C /opt -xvf libPlanckWrapper.tar.gz
    - cp gitlab/debian/planckPythonWrapper-release.conf local.conf
    - make dist -j 4
  artifacts:
    paths:
      - dist/pEp-*.whl
    expire_in: 2 mos
    name: planckPythonWrapper-${WRAPPER_REF}-$CI-COMMIT_BRANCH


debian-develop-release:
  extends: .debian-release
  when: manual
  variables:
    WRAPPER_REF: "develop"

debian-master-release:
  extends: .debian-release
  when: manual
  variables:
    WRAPPER_REF: "master"
